# Generated by Django 4.1.3 on 2022-11-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicbookinglesson',
            name='fulfilled_request',
            field=models.BooleanField(default=False),
        ),
    ]
